# (c) Copyright 2023 Hewlett Packard Enterprise Development LP
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  name: cloudops-druid-zk-monitoring
  namespace: druid
  labels:
    rules: prom-rule
    release: platform-monitoring
spec:
  groups:
    - name: druid-zk-monitoring.rules
      rules:
        - alert: Zookeeper quorum down
          expr: count(count by (instance) (quorum_size)) < max(quorum_size)
          for: 5m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Count of zookeeper pods are less than desired'
            summary: 'Count of zookeeper pods of namespace zk-druid is less'
            runbook: 'https://ccpdocs.ise.hpedevops.net/runbooks/Druid/Zookeeper-Check.html'

        - alert: Zookeeper leader down
          expr: count by (instance) (leader_uptime{app="druid-zookeeper"}) != 1
          for: 5m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Count of zookeeper leader is not in desired number'
            summary: 'Count of leader zookeeper pods of namespace zk-druid is mismatching'
            runbook: 'https://ccpdocs.ise.hpedevops.net/runbooks/Druid/Zookeeper-Check.html'

        - alert: Zookeeper learner down
          expr: max(learners) != (max(quorum_size) - 1)
          for: 5m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Count of zookeeper learner is not in desired number'
            summary: 'Count of learner zookeeper pods of namespace zk-druid is mismatching'
            runbook: 'https://ccpdocs.ise.hpedevops.net/runbooks/Druid/Zookeeper-Check.html'