
# (c) Copyright 2023 Hewlett Packard Enterprise Development LP
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  name: cloudops-druid-monitoring
  namespace: druid
  labels:
    rules: prom-rule
    release: platform-monitoring
spec:
  groups:
    - name: druid.rules
      rules:
        - alert: Druid Pod Status
          expr: sum(kube_pod_status_ready{condition="true",pod=~"druid-(.*)",namespace="druid"}) < count(kube_pod_created{pod=~'druid-(.*)',namespace="druid"})
          for: 5m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Count of druid pods are less than desired'
            summary: 'Druid ready pod count is {{`{{ $value | printf "%.2f" }}`}} less than created count for more than 1 minute'
            runbook: 'https://ccpdocs.cloudops.cloud.hpe.com/docs/runbooks/druid/component-check/'

        - alert: Druid unavailable segment status
          expr: sum(druid_emitted_metrics{metric_name="segment-unavailable-count"}) > 0
          for: 5m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Sum of unavailable segment is greater than 0'
            summary: 'found unavailable segment greater than 0 for more than 1 minute'
            runbook: 'https://ccpdocs.cloudops.cloud.hpe.com/docs/runbooks/druid/unavailable-segments-check/'

        - alert: Druid health status
          expr: druid_health_status{kubernetes_name="druid-exporter"} == 0
          for: 5m
          labels:
            severity: page
            source: cloud
          annotations:
            description: '{{`{{$labels.instance}}`}}: Druid health status is down'
            summary: '{{`{{$labels.instance}}`}}: Druid health status is down for more than 10 minutes'
            runbook: 'https://ccpdocs.cloudops.cloud.hpe.com/docs/runbooks/druid/health-check/'

        - alert: Query failed count in broker pods
          expr: druid_emitted_metrics{metric_name="query-failed-count",service="druid-broker",kubernetes_name="druid-exporter"} > 5
          for: 10m
          labels:
            severity: page
            source: cloud
          annotations:
            description: '{{`{{$labels.instance}}`}} query failed count in broker pods is greater than 5'
            summary: '{{`{{$labels.instance}}`}}: Query failed count in broker pods : {{`{{ $value | printf "%.2f" }}`}}'
            runbook: 'https://ccpdocs.cloudops.cloud.hpe.com/docs/runbooks/druid/task-status/'

        - alert: Query failed count on historical pods
          expr: druid_emitted_metrics{metric_name="query-failed-count",service="druid-historical",kubernetes_name="druid-exporter"} > 5
          for: 10m
          labels:
            severity: page
            source: cloud
          annotations:
            description: '{{`{{$labels.instance}}`}} query failed count in historical pods is greater than 5'
            summary: '{{`{{$labels.instance}}`}}: Query failed count in historical pods : {{`{{ $value | printf "%.2f" }}`}}'
            runbook: 'https://ccpdocs.cloudops.cloud.hpe.com/docs/runbooks/druid/task-status/'

        - alert: Supervisors are in either PENDING or UNABLE_TO_CONNECT_TO_STREAM state
          expr: count(druid_supervisors{state!="RUNNING"}) > 0
          for: 10m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Druid supervisors are either PENDING or UNABLE_TO_CONNECT_TO_STREAM state'
            summary: 'Count of supervisors which are in not running state : {{`{{ $value | printf "%.2f" }}`}}. Please check the Druid UI for identifying the supervisors.'
            runbook: 'https://ccpdocs.cloudops.cloud.hpe.com/docs/runbooks/druid/task-status/'

        - alert: Historical pods Segment storage utilized 80 percent of maximum capacity
          expr: sum(druid_emitted_metrics{service="druid-historical",metric_name="segment-used"}) / sum(druid_emitted_metrics{service="druid-historical",metric_name="segment-max"}) * 100 > 80
          for: 10m
          labels:
            severity: page
            source: cloud
          annotations:
            description: 'Historical pods Segment storage utilized 80 percent of maximum capacity!'
            summary: 'Historical pods Segment storage utilized 80 percent of maximum capacity. To resolve this, please follow 10 steps in the runbook'
            runbook: 'https://hpe.atlassian.net/wiki/x/MgBFdg'