{
 "title": "druid-overview-new",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "segment loadQueue count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ceil(sum(druid_segment_loadqueue_count))",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Query Count Per service",
   "type": "timeseries",
   "description": "This metric allows you to monitor the number of queries being sent to your cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service) (druid_query_count_total)",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Under replicated segment count",
   "type": "timeseries",
   "description": "The number of segments that should be, but are not available on the historicals",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ceil(sum(druid_segment_underreplicated_count))",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Query Failed Count",
   "type": "timeseries",
   "description": "Failing queries might mean a problem with historicals or brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(service) (druid_query_failed_count_tota)",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Segment count",
   "type": "timeseries",
   "description": "The number of segments loaded on each historical will impact its resource consumption.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(druid_historical_segment_count)",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Broker Query Time Per Service in milli seconds",
   "type": "timeseries",
   "description": "A spike in this metric might mean that the historicals or brokers are not keeping up with the queries being sent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(service) (druid_query_time{service=\"druid-broker-metrics\"})",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Druid Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid Exporter",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 25 },
   "options": {
    "content": "<p style=\"text-align:center;\">\n    <img src=\"https://druid.apache.org/img/druid_nav.png\" height=\"60\" width=\"160\">\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "druid_health_status" }
   ]
  },
  {
   "title": "Success Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_task_success_count_total)",
     "legendFormat": "{{`{{ task_status }}`}}"
    }
   ]
  },
  {
   "title": "Unloaded Segments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_segment_loadqueue_count))"
    }
   ]
  },
  {
   "title": "Druid Task's Success Percentage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_task_success_count_total) / (druid_task_success_count_total+druid_task_failed_count_total) * 100"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_task_running_count_total)",
     "legendFormat": "{{`{{ task_status }}`}}"
    }
   ]
  },
  {
   "title": "Total Segments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(druid_segment_count)" }
   ]
  },
  {
   "title": "Total Datasources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(druid_datasource{})" }
   ]
  },
  {
   "title": "Unloaded Segments Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_loadqueue_size)"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_task_failed_count_total)",
     "legendFormat": "{{`{{ task_status }}`}}"
    }
   ]
  },
  {
   "title": "Middlemanager Query Time Per Service in milli seconds",
   "type": "timeseries",
   "description": "A spike in this metric might mean that the historicals or brokers are not keeping up with the queries being sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg by(service) (druid_query_time_count{service=\"druid-middlemanager-metrics\"})",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Router Query Time Per Service in milli seconds",
   "type": "timeseries",
   "description": "A spike in this metric might mean that the historicals or brokers are not keeping up with the queries being sent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "avg by(service) (druid_query_time_count{service=\"druid-router-metrics\"})",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Historical Query Time Per Service in milli seconds",
   "type": "timeseries",
   "description": "A spike in this metric might mean that the historicals or brokers are not keeping up with the queries being sent",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 39 },
   "targets": [
    {
     "expr": "avg by(service) (druid_query_time_count{service=\"druid-historical-metrics\"})",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_pool_used[$__range])) by (service)",
     "legendFormat": "{{`{{ exported_service }}`}}"
    }
   ]
  },
  {
   "title": "JVM Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_jvm_mem_used[$__range]))"
    }
   ]
  },
  {
   "title": "Ingestion Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_ingest_kafka_lag[$__range]))by (host)",
     "legendFormat": "{{`{{ host }}`}}"
    }
   ]
  },
  {
   "title": "Ingestion Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingestion Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_ingest_events_processed_total[$__range]))",
     "legendFormat": "{{`{{ metric_name }}`}}"
    }
   ]
  },
  {
   "title": "Datasource Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_segment_size{}[$__range])) by (datasource_name)",
     "legendFormat": "{{`{{ datasource_name }}`}}"
    }
   ]
  },
  {
   "title": "Druid Datasource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deep Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datasource  Replication Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(druid_segment_replicated_size)"
    }
   ]
  },
  {
   "title": "Replicated Data Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_replicated_size)"
    }
   ]
  },
  {
   "title": "Druid Task Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid Task Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_tasks_duration) by (datasource, task_id, task_status)"
    }
   ]
  }
 ]
}