name: Helm OCI Publish
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  helm-oci-publish:
    name: Helm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Publish
        uses: hpe-actions/helm-oci-publish@v2
        with:
          skip_checkout: true
          path: helm
          repository_path: /druid-exporter

