# This Github action is triggered whenever a pull request is opened, reopened, synchronized or edited. 
# The purpose of the action is to ensure PR titles, branch names and commits messages are kept consistent.
# - Pull request titles must follow the convention: GLCP-????: *
#   - Example: GLCP-XXXX: PR title validation
# - Branch name must follow convention: (feature|bugfix|release|hotfix)/GLCP-????-* or GLCP-????-*
#   - Example: feature/GLCP-XXXX-branch-name-validation or GLCP-XXXX-branch-name-validation
# - Commit message must follow convention: GLCP-????: *
#   - Example: GLCP-XXXX: Add commit message validation

name: GLCP Pull Request Validation
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main
jobs:
  validate_pull_request:
    uses: glcp/ccp-action-pr-validation/.github/workflows/pr-validation.yaml@main
