# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Secrets Scanner

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  secrets-scanner:
    uses: hpe-actions/secrets-scanner/.github/workflows/secrets-scanner.yml@v2